Make push required input on build action (#16)
* make push required input on build action

* Validate image inputs

* pass image tags

* use nonroot

* add nonroot user

* install dev deps

* noonroot owns all the /app files

* fix order

* eff it use root for now.

diff --git a/.github/actions/run/action.yml b/.github/actions/run/action.yml
--- a/.github/actions/run/action.yml
+++ b/.github/actions/run/action.yml
@@ -13,6 +13,17 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        if [[ -z "${{ inputs.image }}" ]]; then
+          echo "Image is required"
+          exit 1
+        fi
+        if [[ -z "${{ inputs.run }}" ]]; then
+          echo "Run is required"
+          exit 1
+        fi
     - name: Run Docker Container
       shell: bash
       run: |
@@ -25,7 +36,7 @@ runs:
         cat <<EOF > root.sh
         #!/bin/bash
         whoami
-        su -s /bin/bash -c './exec.sh' olympia
+        su -s /bin/bash -c './exec.sh' root
         EOF
 
         # Make both files executable
